version: '3.8'

services:
  server:
    build:
      context: './'
      dockerfile: './Dockerfile.dev'
      args:
        # Use PWD so that files in stdout are clickable
        APP_DIR: '${PWD}'
    env_file: '.env'
    environment:
      DATABASE_URL: 'postgres://postgres:password@db/virginity-bot'
      STORAGE_S3_HOST: 'object-storage'
      STORAGE_S3_PORT: '9000'
      STORAGE_S3_SSL: 'false'
      STORAGE_S3_REGION: 'local'
    volumes:
      - './:${PWD}'
    ports:
      - '9229:9229'
    networks:
      - 'virgin-net'
    depends_on:
      - 'db'
      - 'object-storage'
  db:
    image: 'docker.io/library/postgres:15'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'virginity-bot'
    volumes:
      - 'virginity-bot-db:/var/lib/postgresql/data'
    ports:
      - '5432:5432/tcp'
    networks:
      - 'virgin-net'
  object-storage:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'password'
      MINIO_REGION: 'local'
    volumes:
      - 'virginity-bot-object-storage:/data'
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - 'virgin-net'

networks:
  virgin-net:

volumes:
  virginity-bot-db:
  virginity-bot-object-storage:
